---
- name: "Ensure dependencies are installed"
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - "gpgv"
      - "gnupg"
      - "dirmngr"
      - "dconf-cli"
      - "dconf-service"
      - "dbus-x11"
      - "python3-psutil"

- name: "Add repository"
  ansible.builtin.apt_repository:
    repo: "{{ workrave_deb_source }}"
    state: "present"

- name: "Refresh apt sources list"
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 600

- name: "Install Workrave"
  ansible.builtin.apt:
    name: "{{ workrave_package }}"
    state: present

- name: "Setup Workrave"
  community.general.dconf:
    key: "{{ item.key }}"
    value: "'{{ item.value | string }}'"
  loop: "{{ workrave_setup | dict2items }}"
  when: workrave_setup_enable
