---
- name: Converge
  hosts: all
  become: true

  pre_tasks:

    - name: "Refresh apt sources list"
      apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

  roles:
    - role: webarchitect609.workrave
